### ISSUE TITLE
文章模版标签和分类自定义

### ISSUE THREAD

**Issue by srcrs** [xcyeye/aurora-blog#2]
文章模版标签和分类能否设置成自定义
```
---
title: abc
date: 2020-03-07
category: a
tags:
 - a
---
```
不同的主题对于category和tag会有不同的命名，如果能自定义，迁移到本主题会减少一些成本。

**Comment by xcyeye** [comment]
这个可以的，我在下个版本就兼容，你可以先不要改你md文件，等下个版本的时候，直接改下就行

**Comment by srcrs** [comment]
> 这个可以的，我在下个版本就兼容，你可以先不要改你md文件，等下个版本的时候，直接改下就行

感谢

**Comment by xcyeye** [comment]
> > 这个可以的，我在下个版本就兼容，你可以先不要改你md文件，等下个版本的时候，直接改下就行
> 
> 感谢

我刚刚增加了这个功能，但是并没有正式发布，我发布一个beta版本，打算等下次增加其他新功能的时候，一起正式发布，你安装下面这个版本
```sh
npm i vuepress-theme-aurora@1.13.0-beta.2
```

安装之后，你在`docs/.vuepress/config.js`文件里面，增加下面两个配置项，就可以自定义标签还有类别
```js
customTagName: 'tags',
customCategoriesName: "category"
```

**Comment by srcrs** [comment]
> > > 这个可以的，我在下个版本就兼容，你可以先不要改你md文件，等下个版本的时候，直接改下就行
> > 
> > 
> > 感谢
> 
> 我刚刚增加了这个功能，但是并没有正式发布，我发布一个beta版本，打算等下次增加其他新功能的时候，一起正式发布，你安装下面这个版本
> 
> ```shell
> npm i vuepress-theme-aurora@1.13.0-beta.2
> ```
> 
> 安装之后，你在`docs/.vuepress/config.js`文件里面，增加下面两个配置项，就可以自定义标签还有类别
> 
> ```js
> customTagName: 'tags',
> customCategoriesName: "category"
> ```

好的，我试一下

**Comment by srcrs** [comment]
![1281640273746_ pic_hd](https://user-images.githubusercontent.com/49332985/147261929-4c86bf76-e9b1-409e-bd13-0273bb59bfc2.jpg)

新的运行引入了vite，产生了一些报错，按照github readme教程，已无法进入首页

**Comment by xcyeye** [comment]
> ![1281640273746_ pic_hd](https://user-images.githubusercontent.com/49332985/147261929-4c86bf76-e9b1-409e-bd13-0273bb59bfc2.jpg)
> 
> 新的运行引入了vite，产生了一些报错，按照github readme教程，已无法进入首页

这个是因为`coze`这个插件，引入leancloud依赖造成的，使用`vite`做为打包工具，就会出现这个问题，你使用`webpack`作为打包工具就可以了解决，

在`docs/.vuepress/config.js`文件中，加入下面这个，将使用`webpack`作为打包工具
```sh
npm install -D vuepress-webpack@next
```

```js
module.exports = {
    bundler: '@vuepress/bundler-webpack',
}
```
