### ISSUE TITLE
還沒有安裝配置文件嗎？

### ISSUE THREAD

**Issue by changchichung** [xcyeye/aurora-blog#6]
看這個畫面，實在很想玩玩看啊～
可是沒有看到安裝文件，或者是docker 文件
不知道怎麼開始玩...

**Comment by xcyeye** [comment]
> 看這個畫面，實在很想玩玩看啊～
> 可是沒有看到安裝文件，或者是docker 文件
> 不知道怎麼開始玩...

非常抱歉现在才看到，最近在忙着找工作，导致运行文档还没有写，docker也还没有弄
